services:
  postgres:
    image: postgres:16-alpine
    container_name: jobbsie_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobbsie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '6666:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d jobbsie']
      interval: 30s
      timeout: 10s
      retries: 3
